[0m14:30:46.064074 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb3ce376890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb3cc8e7fd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb3cc8e7e80>]}


============================== 14:30:46.067838 | d892d853-a4e6-4319-a634-592963ebe07e ==============================
[0m14:30:46.067838 [info ] [MainThread]: Running with dbt=1.5.0
[0m14:30:46.068303 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/s/lol/lol-bet/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m14:30:46.068721 [error] [MainThread]: Encountered an error:
Runtime Error
  dbt_project.yml does not parse to a dictionary
[0m14:30:46.069226 [debug] [MainThread]: Command `dbt build` failed at 14:30:46.069119 after 0.02 seconds
[0m14:30:46.069502 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb3ce376890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb3cc8e7e80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fb3cc8e7be0>]}
[0m14:30:46.069794 [debug] [MainThread]: Flushing usage events
[0m14:34:34.614943 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc4634ca7d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc461ae3ee0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc461ae3e20>]}


============================== 14:34:34.617551 | 546e4961-5ca2-49dd-842f-c2aab88b857d ==============================
[0m14:34:34.617551 [info ] [MainThread]: Running with dbt=1.5.0
[0m14:34:34.618030 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/s/lol/lol-bet/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m14:34:34.618442 [error] [MainThread]: Encountered an error:
Runtime Error
  dbt_project.yml does not parse to a dictionary
[0m14:34:34.618937 [debug] [MainThread]: Command `dbt build` failed at 14:34:34.618826 after 0.01 seconds
[0m14:34:34.619204 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc4634ca7d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc461ae3e20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc461ae3b20>]}
[0m14:34:34.619507 [debug] [MainThread]: Flushing usage events
[0m14:38:04.741043 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe2afea2860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe2ae4e3e20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe2ae4e3d00>]}


============================== 14:38:04.743958 | 9e915c4a-5c88-4038-a1b5-4479ff27e13b ==============================
[0m14:38:04.743958 [info ] [MainThread]: Running with dbt=1.5.0
[0m14:38:04.744536 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/home/s/lol/lol-bet/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m14:38:04.745026 [info ] [MainThread]: Setting up your profile.
[0m14:38:04.745540 [error] [MainThread]: Encountered an error:
'NoneType' object is not subscriptable
[0m14:38:04.746680 [error] [MainThread]: Traceback (most recent call last):
  File "/home/s/miniconda3/lib/python3.10/site-packages/dbt/cli/requires.py", line 86, in wrapper
    result, success = func(*args, **kwargs)
  File "/home/s/miniconda3/lib/python3.10/site-packages/dbt/cli/requires.py", line 71, in wrapper
    return func(*args, **kwargs)
  File "/home/s/miniconda3/lib/python3.10/site-packages/dbt/cli/main.py", line 459, in init
    results = task.run()
  File "/home/s/miniconda3/lib/python3.10/site-packages/dbt/task/init.py", line 262, in run
    profile_name = self.get_profile_name_from_current_project()
  File "/home/s/miniconda3/lib/python3.10/site-packages/dbt/task/init.py", line 141, in get_profile_name_from_current_project
    return dbt_project["profile"]
TypeError: 'NoneType' object is not subscriptable

[0m14:38:04.747278 [debug] [MainThread]: Command `dbt init` failed at 14:38:04.747173 after 0.01 seconds
[0m14:38:04.747610 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe2afea2860>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe2ae4e3d90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe2ae4e3400>]}
[0m14:38:04.747925 [debug] [MainThread]: Flushing usage events
